### ISSUE TITLE
MORT crashes after loading

### ISSUE THREAD

**Issue by azra1l** [PennyDreadfulMTG/MagicOnlineReplayTool#4]
If i run the exe, it appears to import and load some stuff, and then quits without any further interaction. 
No window left, no icon in systray either. 

I have lots of replays listed in MTGO, also played a game and tried again, same result.

The original author disappeared along with his tool, so happy to see it live again!
I've been waiting for this to be re-released ever since i read about it.

**Comment by azra1l** [comment]
Running Windows 11 Professional 21H2, MTGO with latest updates.

**Comment by azra1l** [comment]
I checked eventlog, and the crash is listed there.
Gathered the following XML data:

`[-](https://github.com/PennyDreadfulMTG/MagicOnlineReplayTool/issues/4#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/PennyDreadfulMTG/MagicOnlineReplayTool/issues/4#) <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-10-04T21:56:36.9902063Z" /> 
  <EventRecordID>1175006</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="6692" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>SUPERNOVA</Computer> 
  <Security /> 
  </System>
[-](https://github.com/PennyDreadfulMTG/MagicOnlineReplayTool/issues/4#) <EventData>
  <Data>2117936965271969543</Data> 
  <Data>5</Data> 
  <Data>CLR20r3</Data> 
  <Data>Nicht verfügbar</Data> 
  <Data>0</Data> 
  <Data>MORT.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>61fb34a5</Data> 
  <Data>System.Core</Data> 
  <Data>4.8.4536.0</Data> 
  <Data>62a12823</Data> 
  <Data>bbf</Data> 
  <Data>b5</Data> 
  <Data>System.InvalidOperationException</Data> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.05150506-a63a-4ead-9337-1c091499e7df.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.58420b07-d821-4291-bd6a-396ce24e4457.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e423e7ae-d0d2-483e-87cb-1a232fb2694b.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.79cccd22-6222-4325-bd8b-90b608619be5.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e5f3d5e5-6311-4da0-8959-40f56ef6f9e9.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MORT.exe_d3bf8a74fa4df0ed8732bb9825bfbacec575d947_e2987425_d980b110-7603-4658-ae96-70cb2608888b</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>3f9bb18c-9c85-4337-987e-0302b5918485</Data> 
  <Data>268435456</Data> 
  <Data>0b9fe41c4a4d30e1ed646c72d7b45f07</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>`

I can upload any of these files if needed.

**Comment by silasary** [comment]
Can you send me your replays folder? 

The crash dump (the dmp file in that xml) would also be useful, if you still have it

**Comment by silasary** [comment]
I think I fixed this.  Can you try [2.2.0](https://github.com/PennyDreadfulMTG/MagicOnlineReplayTool/releases/tag/v2.2.0) and tell me if it works now?

**Comment by azra1l** [comment]
Hi,

sorry had no time to get back to you yet. I just reinstalled the client for
the transition and apparently that also wiped all my previous games. Welp.
I will try your new version and see if I can still reproduce the error and
send you the files if the problem persists.

Thanks in advance!
LG

**Comment by azra1l** [comment]
Hi, so the crash is gone, that's a start :)

But now i'm still somewhat lost as in how to use this thing, appears it doesn't recognize my replays. I will open another issue.
